dist: trusty
sudo: required
language: python
python:
- '2.7'
#addons:
#  apt:
#    packages:
#    - ansible
env:
- MYHOME=/home/travis/build/Otus-DevOps-2018-02/ivanov2103_infra
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh|bash
install:
- sudo pip install ansible
- sudo pip install ansible-lint
- cd /tmp
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- unzip terraform_0.11.7_linux_amd64.zip
- wget https://github.com/wata727/tflint/releases/download/v0.6.0/tflint_linux_amd64.zip
- unzip tflint_linux_amd64.zip
- sudo mv terraform tflint /usr/local/bin/
- rm -rf terraform* tflint*
before_script:
- cd $MYHOME
- touch /home/travis/.ssh/appuser.pub
- cp packer/variables.json.example packer/variables.json
- cp terraform/prod/terraform.tfvars.example terraform/prod/terraform.tfvars
- cp terraform/stage/terraform.tfvars.example terraform/stage/terraform.tfvars
script:
- for file in `find packer/ -type f -name "*.json" ! -name variables.json`; do packer validate -var-file=packer/variables.json $file; done
- find terraform/ -type f -name "*.tf" | tflint
- cd $MYHOME/terraform/stage/ ; mv backend.tf backend.tf.example && terraform init && terraform validate
- cd $MYHOME/terraform/prod/ ; mv backend.tf backend.tf.example && terraform init && terraform validate
- cd $MYHOME
- for file in `find ansible/ -type f -name "*.yml" ! -path "*jdauphant*"`; do ansible-lint $file; done
notifications:
  slack:
    secure: k1AcK+KVlqRZ1giHE8ZZPZs9CCVnNJA19ucLKs1gnwWU8Cz3P5gi+Kkow90IK89LgVw1Fl838feK3Pb1xTaVszR9eZZrbwfvCfx6+zmF+QLqasx1jBcAsrjgGEUsvhDVrN4c74OPS9/apQ4icpbsYd8rrEdN15fkbPB4cL8xKWHQZfMOuNreU8YKc5B4I9eC8LC6W89V/cn5sNwWtnldClGiGbb485g4DfPMIxTmcIfVO5w1cx9ayLK065vRsgGt8aN6/RUM101mpiU6YWb+q86B2uHaU3VYj/dUk8SnRvpSbeXf4FZm5QAD23oX0Q1cLG4j/mP05Ww4OG6kOIEZewX9dR61+6fN7mORmAizfoJ8jiVW71Gzm7MHqtEP2ch9CvbUK/yGXs67/j7v86X3qlVMQ8sSWNPMcx+JfzURfCMOahxqfcBfftrd0kSPH7IRtbTsNby8vBxnwCQdpMNEr3av318R6QugldrqG6bSxVTdaFDJS0fd2G2RuI6LktREm+viOmukUS7fncKuXhjrGZ8blBDOEVDSj4/qhT4XWuJdGZ5jU44rEb186ItgriJ3AMUO16iljFDKxV4pnTlxxkHEYw2cjEFhhu0JjFbMxNsw9FFUQHKvwqUdZvYrpeVhCQkblORboJNMCBD1fOyAlpGKgHyVM1OmyLQnhtKT5qw=
